---
title: "data_assignment"
format: pdf
author: Mia Minkin
editor: visual
---

## **Part 1: Question of Interest**

-   Of children experiencing poverty in Florida in 2019, which race was reached most?

## **Part 2: Data Sets**

-   To measure this, information needed:

    -   Poverty rate by race in Florida in 2019

    -   Florida children in poverty reached by TANF by race in 2019

#### Data Set 1: American Community Survey (2019)

1.  How the data are created

    -   The data are created through survey data collected by the U.S. Census Bureau every year. Surveys are conducted via internet, mail, phone, and in-person interviews.

2.  Data dictionary

    -   There is a clear data dictionary provided for the American Census Survey.

3.  Unit of analysis

    -   Individuals respond to the survey on behalf of their entire household.

4.  Dimensions of data

    -   In 2019, there was a response rate of 86%

    -   Total sample size of 2,210,250 respondents in 2019

    -   Four sections of questions in survey

        -   First: basic address information

        -   Second: Basic demographic data

        -   Third: Housing information

        -   Fourth: Population data

5.  Missing values in data

    -   There may be missing values for questions respondents did not answer for a variety of reasons.

6.  Data limitations

    -   As with any data set that relies on collecting data via respondents, it is important to consider the demographics of individuals who are more likely to respond as well as individuals who have access to responding to the survey. This should be taken into consideration when making inferences from the data alongside the methods the institution (the U.S. Census Bureau) takes into account to address these issues.

#### Data Set 2: Kids Count Data Center (2019)

1.  How the data are created

    -   Tool created by using the American Community Survey. Separated into relevant information to provide data on specific issues and demographics of children in the United States.

2.  Data dictionary

    -   Data definitions are provided in each year's Kids Count Data book.

3.  Unit of analysis

    -   Focused on children and individuals across the nation.

4.  Dimensions of data

    -   Same as the American Community Survey, however, not focused on all of the issues included in the American Community Survey- just what relates to child well-being.

    ```{=html}
    <!-- -->
    ```
    -   In 2019, there was a response rate of 86%

    -   Total sample size of 2,210,250 respondents in 2019

5.  Missing values in data

    -   Same as the ACS, the may be missing values for questions respondents did not answer for a variety of reasons.

6.  Data limitations

    -   In terms of different data limitations beyond what exists from ACS, it is also important to consider that respondents of ACS were not children directly, they were adults answering on behalf of their household, meaning there may be some inaccuracy between true responses and demographics and what was reported/collected through respondent surveys.

#### Data Set 3: State TANF Report (Florida FY2019)

1.  How the data are created

    -   Congressional Research Service tabulations of FY2019 TANF data files.

2.  Data dictionary

    -   No clear data dictionary provided, but data is provided in labeled tables that clearly clarify the data being presented.

3.  Unit of analysis

    -   Household, family level, adult, and children level data.

4.  Dimensions of data

    -   Includes data of all TANF recipients across states. Includes age level data, race/ethnicity, work/education data, and more demographic information regarding recipients of TANF.

5.  Missing values in data

    -   None in the data set, however, the data presented comes from raw data files and data may be missing in those, however, it comes straight from the program delivery agency, which indicates that it is accurate since individuals receiving TANF had to file paperwork to receive benefits.

6.  Data limitations

    -   The data provided are already tabulated and from prior experience conducting research in TANF, raw data is not available directly. This is a direct limitation as individuals are not able to directly collect information regarding TANF, however, this also may be for privacy purposes.
